language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - AWS_DEFAULT_REGION=ap-southeast-2
    - LAMBDA_NAME=awsBillingAlerts
    - LAMBDA_ALIAS=prod
    - SNS_TOPIC=arn:aws:sns:ap-southeast-2:300761597318:admin-notifications
    - BUCKET_NAME=chr-admin

    # AWS_SECRET_ACCESS_KEY
    - secure: r4YtOjeasOuLOGlikegcl003Eh3W2voEsI8Im0gFPLtfl+3MDum+UewmIc1Q0LInkKXPblBCNZBv8J+2FNDjMArqsetmFzsww+tL+4pQgTTMH9wa+OfhcTMI+EWwzBJEIXzW+i1l94knQLtFP6bk8tMai260Up6GXZRw+tf2S8KWz6IHH1EpkwErKKI1QlpySBD5TE4C272emlhdO/hz1k0nEbU+hTlfhrdy8CkSGCkms9oDbl9X7Ug7zp4uWPjhRbG8payO+PNjwkciF949U8Q6zA2socFGeFgjIbEx8SPHC98B/+gOfxaWO4V02D6POzMDRv2HmGYgADQszT+3QJr1BMnPLA4Q0rbwYsmzjorNCbcPhHBl+j08CtFBTCqMpepSycI/5SjpBVeuebFxYZmbRESthYWUkKgRWVh75yHcaChSG3eyQg3LKm6bOak2Cnh/LF2DSIHemyGHAOHq/tPI6WYdwlkcyfrxGLDICsjNHIRCsNaOO/TEpTMgHCv4Pf93PEFAJZzRNKx//Bs1udyIl61396mzsIKCeWF24cz+hNV9QYq0SJ3BmZykQof8sv0czJM+/HGf16t9xpdH25gfGKQL9c1Kl7OoUMPGq7cg7qHuQaT09mrEE5YzLz5hTRhiNtQIQm3G/KjXBx1ZBW8jTuRYoonU4Ulc0oDjfbk=

cache:
  yarn: true
  directories:
    - node_modules

install: yarn

script:
  - yarn lint
  - yarn test

before_deploy: yarn remove aws-sdk && rm -rf coverage node_modules tests .*rcs.js && yarn --prod

deploy:

  # Deploy to $LATEST on chromatix branch.

  - on:
      branch: chromatix
    publish: false

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: arn:aws:iam::300761597318:role/genericLambdaRole
    description: Sends SNS alerts when the current month's bill changes.
    runtime: nodejs6.10
    timeout: 30
    handler_name: handler
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
